CREATE SCHEMA RETAILBANK;

CREATE TABLE RETAILBANK.CUSTOMER_PROFILE(CUSTOMER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                                     FIRST_NAME VARCHAR(100)  NOT NULL,
                                     MIDDLE_NAME VARCHAR(100),
                                     LAST_NAME VARCHAR(100),
                                     ADDRESS_LINE1 VARCHAR(100),
                                     ADDRESS_LINE2 VARCHAR(100),
                                     CITY VARCHAR(100),
                                     STATE VARCHAR(100),
                                     ZIPCODE NUMERIC (10)
                                     
);

INSERT INTO RETAILBANK.CUSTOMER_PROFILE (CUSTOMER_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS_LINE1,CITY,STATE,ZIPCODE) VALUES (1,'Kalaiarasan','C','Subramanian','PlaceinCbe','Coimbatore','TanmilNadu','641045');